#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  mapperLocations: classpath:mapper/*.xml



---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test2?serverTimezone=GMT%2B8
    username: root
    password: 9520
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
  servlet:
    multipart:
      max-file-size: 104857600
      
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址  
    host: 192.168.2.128
    # Redis服务器连接端口  
    port: 6379
    # Redis服务器连接密码（默认为空）  
    password: 
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）  
        max-wait: -1
        # 连接池中的最大空闲连接  
        max-idle: 10
        # 连接池中的最小空闲连接 
        min-idle: 0
    # 连接超时时间（毫秒）  
    timeout: 1000
      
server:
  port: 8888
      

    
    

    
